name: 'Neo | Config File'
type: module
description: 'Provides the ability to store files in config.'
package: Neo
version: 1.0.6
core_version_requirement: ^10.3 || ^11
dependencies:
  - drupal:file
  - neo:neo
configure: entity.neo_config_file.collection
